{-
    Consider all integer combinations of a^b for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:

    2^2=4, 23=8, 24=16, 25=32
    32=9, 33=27, 34=81, 35=243
    42=16, 43=64, 44=256, 45=1024
    52=25, 53=125, 54=625, 55=3125
    If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

    4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

    How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
-}
-- Strat 1: brute force
-- Strat 2: 99x99 minus counting argument for duplicates. Count powers below 7 (2^7 > 100)

import Data.Containers.ListUtils (nubOrd)

dedupe xs = nubOrd xs
nTerms n = length $ dedupe [ a^b | a <-[2..n], b <-[2..n] ]

answer = nTerms 100

main = do
    print $ nTerms 5 == 15
    print $ answer
    print $ [ (a,b) | a <-[1..10], b <-[1..a] ]