{-
    Pentagonal numbers are generated by Pn=n(3n−1)/2. 
    The first ten pentagonal numbers are:   1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

    It can be seen that P4 + P7 = 22 + 70 = 92 = P8. 
    However, their difference, 70 − 22 = 48, is not pentagonal.

    Find the pair of pentagonal numbers, Pj and Pk, 
    for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; 
    what is D?
-}

-- Strat 1: gen list, check membership, double loop
-- Strat 2: take the inverse of the pent formula, check int solutions 

{-
    inverse
    P  = n(3n−1)/2
    0 = 3n^2 - n - 2P
    As quadratic:    a = 3, b = -1, c = -2P

    n = [1 + \sqrt (1 + 24P)] / 6
-}

pentagonal n = n * (3*n - 1) / 2
pents = map pentagonal [1..]
isInt x = x == fromInteger (round x)
isPent n = isInt $ (sqrt(24 * n + 1) + 1) / 6
diff a b = round $ abs (a - b)

-- `reverse' is key to actually answering the question
answer = head [ diff a b | 
                a <- pents,
                b <- reverse $ takeWhile (<a) pents,
                isPent (a-b),
                isPent (b+a) ]


main = do
    let p i = pentagonal i
    let test i j = isPent(p i + p j) && isPent(p j - p i)
    print $ test 4 7 == False
    print $ answer
